routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout');

Route::group(['middleware'=>'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('siswa', 'SiswaController');
    Route::get('download-qrcode/{id}', 'SiswaController@downloadQrcode')->name('downloadqrcode.siswa');
    Route::resource('kelas', 'KelasController');
    Route::resource('presensi', 'PresensiController', ['only' => ['index', 'create', 'store','update']]);
    Route::resource('mutasi', 'MutasiController');
    Route::resource('akademik', 'AkademikController');
    Route::get('/pengaturan', 'PengaturanController@index')->name('pengaturan.index');
    Route::post('/pengaturan', 'PengaturanController@update')->name('pengaturan.update');

    Route::get('laporan', 'PresensiController@laporan')->name('laporan.presensi');
    Route::any('scan-qrcode', 'PresensiController@scanQrcode')->name('scanqrcode.presensi');
});

app/Models/Presensi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Presensi extends Model
{
    protected $table = 'presensi';
    protected $fillable = ['tanggal','siswa_id','kelas_id','akademik_id','status',
        'jam_masuk','jam_pulang','keterangan'];
    protected $dates = ['tanggal'];

    public function siswa()
    {
        return $this->belongsTo('App\Models\Siswa');
    }

    public function kelas()
    {
        return $this->belongsTo('App\Models\Kelas');
    }

    public function akademik()
    {
        return $this->belongsTo('App\Models\Akademik');
    }
}

app/Http/Controllers/PresensiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Presensi;
use App\Models\Siswa;
use App\Models\Akademik;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class PresensiController extends Controller
{
    public function index(Request $request, Builder $htmlBuilder)
    {
        if ($request->ajax()) {
            $presensi = Presensi::with([
                'siswa' => function($query) {
                    $query->select('id','nis','nama');
                },
                'kelas'])->orderBy('created_at','desc');

            return Datatables::of($presensi)
                ->editColumn('tanggal', function($presensi) {
                    return $presensi->tanggal ? $presensi->tanggal->format('d/m/Y') : '';
                })
                ->editColumn('status', function($presensi) {
                    return '<div class="presensi-group btn-group" data-toggle="buttons">
                        <label class="btn btn-default '.($presensi->status =='H' ? 'btn-success active' : '').'">
                          <input type="radio" name="presensi" data-value="H" data-presensi="'.$presensi->id.'"> Hadir
                        </label>
                        <label class="btn btn-default '.($presensi->status =='S' ? 'btn-success active' : '').'">
                          <input type="radio" name="presensi" data-value="S" data-presensi="'.$presensi->id.'"> Sakit
                        </label>
                        <label class="btn btn-default '.($presensi->status =='I' ? 'btn-success active' : '').'">
                          <input type="radio" name="presensi" data-value="I" data-presensi="'.$presensi->id.'"> Izin
                        </label>
                        <label class="btn btn-default '.($presensi->status =='A' ? 'btn-success active' : '').'">
                          <input type="radio" name="presensi" data-value="A" data-presensi="'.$presensi->id.'"> Alpha
                        </label>
                      </div>';
                })
                ->make(true);
        }

        $html = $htmlBuilder
            ->addColumn(['data'=>'tanggal','name'=>'tanggal','title'=>'Tanggal','class'=>'all'])
            ->addColumn(['data'=>'siswa.nis','name'=>'siswa.nis','title'=>'No Induk','class'=>'all'])
            ->addColumn(['data'=>'siswa.nama','name'=>'siswa.nama','title'=>'Nama Lengkap','class'=>'all','width'=>'35%'])
            ->addColumn(['data'=>'kelas.deskripsi','name'=>'kelas.deskripsi','title'=>'Kelas','class'=>'all'])
            ->addColumn(['data'=>'status','name'=>'status','title'=>'Absen','class'=>'all']);

        return view('presensi.index')->with(compact('html'));
    }

    public function laporan()
    {
        return view("presensi.laporan");
    }

    public function scanQrcode(Request $request)
    {
        if ($request->ajax()) {
            $qrcode = $request->get('qrcode');
            $tanggal = date('Y-m-d');
            $jam = date('H:i:s');
            $akademik_id = Akademik::whereAktif(1)->orderBy('created_at','desc')->first()->id;

            if ($siswa = Siswa::where('kode_qr', $qrcode)->first()) {
                if (!$siswa->presensi()->where('tanggal', $tanggal)->count()) {
                    $presensi = $siswa->presensi()->save(new Presensi([
                        'tanggal' => $tanggal,
                        'kelas_id' => $siswa->kelas_id,
                        'akademik_id' => $akademik_id,
                        'status' => 'H',
                        'jam_masuk' => $jam,
                        'jam_pulang' => '00:00:00',
                    ]));
                    return json_encode(['status'=>'success', 'data'=>['nis'=>$siswa->nis, 'nama'=>$siswa->nama, 'kelas'=>$siswa->kelas->deskripsi, 'jam'=>$jam]]);
                }
                return json_encode(['status'=>'recorded']);
            }
            return json_encode(['status'=>'failed']);
        }

        $presensi = Presensi::with([
            'siswa' => function($query) {
                $query->select('id','nis','nama');
            },
            'kelas'])
            ->where('tanggal',date('Y-m-d'))
            ->where('status','H')
            ->orderBy('created_at','desc')->get();
        return view('presensi.scanqrcode')->with(compact('presensi'));
    }

    public function create()
    {
        $siswa = Siswa::aktif()->with(['presensi'=>function($query) {
            return $query->where('tanggal',date('Y-m-d'));
        }])->select('id','nama')->get()->filter(function($siswa) {
            return $siswa->presensi->count() == 0;
        })->pluck('nama','id')->toArray();

        return view('presensi.create')->with(compact('siswa'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'siswa_id' => 'required',
            'status' => 'required|in:H,I,S,A'
        ], [
            'siswa_id.required' => 'Data Siswa harus diisi',
            'status.required' => 'Status harus diisi',
            'status.in' => 'Pilihan status hanya Hadir, Izin, Sakit dan Alpha'
        ]);

        $siswa_id = $request->get('siswa_id');
        $status = $request->get('status');
        $tanggal = date('Y-m-d');
        $jam = date('H:i:s');
        $akademik_id = Akademik::whereAktif(1)->orderBy('created_at','desc')->first()->id;

        if ($siswa = Siswa::findOrFail($siswa_id)) {
            $siswa->presensi()->firstOrCreate([
                'tanggal' => $tanggal,
                'kelas_id' => $siswa->kelas_id,
                'akademik_id' => $akademik_id,
                'status' => $status,
                'jam_masuk' => $jam,
                'jam_pulang' => '00:00:00',
            ]);

            $request->session()->flash('flash_notification', [
                'level' => 'success',
                'message' => 'Berhasil menyimpan data presensi'
            ]);
        } else {
            $request->session()->flash('flash_notification', [
                'level' => 'danger',
                'message' => 'Data siswa tidak ditemukan'
            ]);
        }

        return redirect()->route('presensi.index');
    }

    public function update(Request $request, $id)
    {
        $presensi = Presensi::findOrFail($id);
        $updated = $presensi->update([
            'status' => $request->get('status')
        ]);

        if ($updated) {
            return response()->json([
                'status' => 'success',
            ]);   
        } else {
            return response()->json([
                'status' => 'failed',
            ]);   
        }
    }

}

resources/views/presensi/_form.blade.php
<div class="form-body">
    @include('layouts._flash')

    <div class="form-group {{ $errors->has('siswa_id') ? 'has-error' : '' }}"">
        {!! Form::label('siswa_id','Siswa',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-4">
            {!! Form::select('siswa_id', [''=>''] + $siswa, null, ['class'=>'form-control select2me']) !!}
            {!! $errors->first('siswa_id', '<p class="help-block">:message</p>') !!}
        </div>
    </div>

    <div class="form-group {{ $errors->has('status') ? 'has-error' : '' }}"">
        {!! Form::label('status','Status',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-4">
            <div class="radio-list">
                <label class="radio-inline">
                    {{ Form::radio('status','H', null)}}  Hadir 
                </label>
                <label class="radio-inline">
                    {{ Form::radio('status','I', null)}}  Izin
                </label>
                <label class="radio-inline">
                    {{ Form::radio('status','S', null)}}  Sakit
                </label>
                <label class="radio-inline">
                    {{ Form::radio('status','A', null)}}  Alpha
                </label>
            </div>
            {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>
<div class="form-actions">
    <div class="row">
        <div class="col-md-offset-3 col-md-9">
            <button type="submit" class="btn green">Submit</button>
            <a href="{{ URL::previous() }}" type="button" class="btn default">Cancel</a>
        </div>
    </div>
</div>  

resources/views/presensi/create.blade.php
@extends('layouts.app')

@section('content')
<div class="page-content">
    <div class="page-head">
        <div class="page-title">
            <h1>Input Presensi</h1>
        </div>
        <div class="page-toolbar">
            @yield('page-toolbar')
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Dashboard</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('siswa.index') }}">Data Presensi</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Tambah</span>
        </li>
    </ul>

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-fit portlet-form bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-users font-green"></i>
                        <span class="caption-subject bold uppercase">Tambah Presensi</span>
                    </div>
                    <div class="tools"> </div>
                </div>
                <div class="portlet-body">
                    {!! Form::open(['url'=>route('presensi.store'), 'method'=>'POST', 'class'=>'form-horizontal']) !!}
                        @include('presensi._form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/presensi/index.blade.php
@extends('layouts.app')

@section('page-actions')
<div class="page-actions">
    <div class="btn-group">
        <button type="button" class="btn red-haze btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
            <span class="hidden-sm hidden-xs">Tambah&nbsp;</span>
            <i class="fa fa-angle-down"></i>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li>
                <a href="{{ route('presensi.create') }}">
                    <i class="icon-plus"></i> Tambah 
                </a>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="icon-cloud-upload"></i> Import 
                </a>
            </li>
        </ul>
    </div>
</div>
@endsection

@section('content')
<div class="page-content">
    <div class="page-head">
        <div class="page-title">
            <h1>Data Presensi</h1>
        </div>
        <div class="page-toolbar">
            @yield('page-toolbar')
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Dashboard</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Presensi</span>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Data Presensi</span>
        </li>
    </ul>
    @include('layouts._flash')

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-settings font-green"></i>
                        <span class="caption-subject bold uppercase">Presensi</span>
                    </div>
                    <div class="tools"> </div>
                </div>
                <div class="portlet-body">
                    <div class="table-responsive">
                        {!! $html->table(['class'=>'table table-striped table-bordered table-hover dt-responsive','width'=>'100%']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
{!! $html->scripts() !!}
@endsection

resources/views/presensi/laporan.blade.php
@extends('layouts.app')

resources/views/presensi/scanqrcode.blade.php
@extends('layouts.presensi')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-settings font-green"></i>
                        <span class="caption-subject bold uppercase">Presensi</span>
                    </div>
                    <div class="tools"> 
                        <a href="" class="fullscreen"> </a>
                    </div>
                </div>
                <div class="portlet-body" style="min-height:100%">
                    <div class="row">
                        <div class="col-md-4">
                            <div id="reader" class="well" style="width:100%;height:330px" ></div>
                            <p id="presensi-debug" class="text-center text-danger"></p>
                        </div>
                        <div class="col-md-8 fill">
                            <h1 id="timeLabel">12:00:00</h1>
                            <p> {{ date('l, d F Y') }}</p>
                            <div class="table-responsive">
                            <table class="table table-bordered table-striped" id="presensi-table">
                                <thead>
                                    <tr>
                                        <th>NIS</th>
                                        <th>Nama</th>
                                        <th>Kelas</th>
                                        <th>Jam Masuk</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($presensi as $absen)
                                        <tr>
                                            <td>{{ $absen->siswa->nis }}</td>
                                            <td>{{ $absen->siswa->nama }}</td>
                                            <td>{{ $absen->kelas->deskripsi }}</td>
                                            <td>{{ $absen->jam_masuk }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .fill { 
    min-height: 100%;
    height: 100%;
}
    </style>
@endsection

@section('scripts')
<script>
function startTime() {
    var today = new Date();
    var h = today.getHours();
    var m = today.getMinutes();
    var s = today.getSeconds();
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('timeLabel').innerHTML =
    h + ":" + m + ":" + s;
    var t = setTimeout(startTime, 500);
}
function checkTime(i) {
    if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;
}
$(function(){
    startTime();
})
</script>
@endsection