routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout');

Route::group(['middleware'=>'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('siswa', 'SiswaController');
    Route::get('download-qrcode/{id}', 'SiswaController@downloadQrcode')->name('downloadqrcode.siswa');
    Route::resource('kelas', 'KelasController');
    Route::resource('presensi', 'PresensiController', ['only' => ['index', 'create', 'store','update']]);
    Route::resource('mutasi', 'MutasiController');
    Route::resource('akademik', 'AkademikController');
    Route::get('/pengaturan', 'PengaturanController@index')->name('pengaturan.index');
    Route::post('/pengaturan', 'PengaturanController@update')->name('pengaturan.update');

    Route::get('laporan', 'PresensiController@laporan')->name('laporan.presensi');
    Route::any('scan-qrcode', 'PresensiController@scanQrcode')->name('scanqrcode.presensi');
});

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    protected $table = 'siswa';
    protected $fillable = ['nis','nama','alamat','jenis_kelamin','tempat_lahir',
        'tanggal_lahir','nama_ortu','hp_ortu','kelas_id','aktif'];

    protected $casts = [
        'aktif' => 'boolean'
    ];

    public static function boot()
    {
        parent::boot();

        self::creating(function($siswa) {
            $siswa->kode_qr = \Hash::make($siswa->nis.date('Y-m-d'));
        });
    }

    public function kelas()
    {
        return $this->belongsTo('App\Models\Kelas');
    }

    public function presensi()
    {
        return $this->hasMany('App\Models\Presensi');
    }

    public function getTanggalLahirAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d', $date)->format('d-m-Y');
    }

    public function setTanggalLahirAttribute($date)
    {
        $this->attributes['tanggal_lahir'] = \Carbon\Carbon::createFromFormat('d-m-Y', $date)->format('Y-m-d');
    }

    public function scopeAktif($query)
    {
        return $query->where('aktif', 1);
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Siswa;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use \App\Http\Requests\SiswaFormRequest;

class SiswaController extends Controller
{
    public function index(Request $request, Builder $htmlBuilder)
    {
        if ($request->ajax()) {
            return Datatables::of(Siswa::with('kelas')->orderBy('id','desc'))
                ->editColumn('aktif', function($siswa) {
                    return $siswa->aktif ? 'Aktif' : 'Tidak Aktif';
                })
                ->addColumn('action', function($siswa) {
                    return view('vendor.datatables._action', [
                        'show_url' => route('siswa.show', $siswa->id),
                        'edit_url' => route('siswa.edit', $siswa->id),
                        'model' => $siswa,
                        'form_url' => route('siswa.destroy', $siswa->id),
                        'confirm_message' => 'Anda yakin ingin menghapus '.$siswa->nama.'?'
                    ]);
                })
                ->make(true);
        }

        $html = $htmlBuilder
            ->addColumn(['data'=>'id','name'=>'id','title'=>'ID','class'=>'all'])
            ->addColumn(['data'=>'nis','name'=>'nis','title'=>'NIS','class'=>'all'])
            ->addColumn(['data'=>'nama','name'=>'nama','title'=>'Nama Lengkap','class'=>'all'])
            ->addColumn(['data'=>'kelas.deskripsi','name'=>'kelas.deskripsi','title'=>'Kelas','class'=>'all'])
            ->addColumn(['data'=>'alamat','name'=>'alamat','title'=>'Alamat','class'=>'none'])
            ->addColumn(['data'=>'jenis_kelamin','name'=>'jenis_kelamin','title'=>'Jenis Kelamin','class'=>'all'])
            ->addColumn(['data'=>'tempat_lahir','name'=>'tempat_lahir','title'=>'Tempat Lahir','class'=>'none'])
            ->addColumn(['data'=>'tanggal_lahir','name'=>'tanggal_lahir','title'=>'Tanggal Lahir','class'=>'none'])
            ->addColumn(['data'=>'nama_ortu','name'=>'nama_ortu','title'=>'Nama Orang Tua','class'=>'none'])
            ->addColumn(['data'=>'hp_ortu','name'=>'hp_ortu','title'=>'No HP Orang Tua','class'=>'all'])
            ->addColumn(['data'=>'aktif','name'=>'aktif','title'=>'Aktif','class'=>'none'])
            ->addColumn(['data'=>'action','name'=>'action','title'=>'Action']);

        return view('siswa.index')->with(compact('html'));
    }

    public function create()
    {
        return view('siswa.create');
    }

    public function store(SiswaFormRequest $request)
    {
        $siswa = Siswa::create($request->all());

        $request->session()->flash('flash_notification', [
            'level' => 'success',
            'message' => 'Berhasil menyimpan '. $siswa->nama
        ]);

        return redirect()->route('siswa.index');
    }

    public function edit($id)
    {
        $siswa = Siswa::findOrFail($id);
        return view('siswa.edit')->with(compact('siswa'));
    }

    public function update(SiswaFormRequest $request, $id)
    {
        $siswa = Siswa::findOrFail($id);
        $siswa->update($request->all());

        $request->session()->flash('flash_notification', [
            'level' => 'success',
            'message' => 'Berhasil menyimpan '. $siswa->nama
        ]);

        return redirect()->route('siswa.index');
    }

    public function show($id)
    {
        $siswa = Siswa::findOrFail($id);
        return view('siswa.show')->with(compact('siswa'));
    }

    public function destroy(Request $request, $id)
    {
        Siswa::destroy($id);

        $request->session()->flash('flash_notification', [
            'level' => 'success',
            'message' => 'Data berhasil dihapus'
        ]);

        return redirect()->route('siswa.index');
    }

    public function downloadQrcode($id)
    {
        $siswa = Siswa::findOrFail($id);
        $data = base64_decode('data:image/png;base64,'.\QrCode::format('png')->size(300)->generate($siswa->kode_qr));

        $im = imagecreatefromstring($data);
        if ($im !== false) {
            header('Content-Type: image/png');
            imagepng($im);
            imagedestroy($im);
        }
        else {
            echo 'An error occurred.';
        }
    }
}

resources/views/siswa/_form.blade.php
<div class="form-body">
    @include('layouts._flash')

    <div class="form-group {{ $errors->has('nis') ? 'has-error' : '' }}">
        {!! Form::label('nis','No Induk',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-4">
            {!! Form::text('nis', null, ['class'=>'form-control']) !!}
            {!! $errors->first('nis', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('nama') ? 'has-error' : '' }}">
        {!! Form::label('nama','Nama Siswa',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-6">
            {!! Form::text('nama', null, ['class'=>'form-control']) !!}
            {!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('alamat') ? 'has-error' : '' }}">
        {!! Form::label('alamat','Alamat',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-6">
            {!! Form::textarea('alamat', null, ['class'=>'form-control','rows'=>'5']) !!}
            {!! $errors->first('alamat', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('jenis_kelamin') ? 'has-error' : '' }}"">
        {!! Form::label('jenis_kelamin','Jenis Kelamin',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-4">
            {!! Form::select('jenis_kelamin', [''=>'-- Pilih Jenis Kelamin--', 'L'=>'Laki-Laki','P'=>'Perempuan'], null, ['class'=>'form-control']) !!}
            {!! $errors->first('jenis_kelamin', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('tempat_lahir') ? 'has-error' : '' }}">
        {!! Form::label('tempat_lahir','Tempat Lahir',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-4">
            {!! Form::text('tempat_lahir', null, ['class'=>'form-control']) !!}
            {!! $errors->first('tempat_lahir', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('tanggal_lahir') ? 'has-error' : '' }}">
        {!! Form::label('tanggal_lahir','Tanggal Lahir',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-4">
            <div class="input-group date date-picker" data-date-format="dd-mm-yyyy">
                {!! Form::text('tanggal_lahir', null, ['class'=>'form-control','readonly'=>'readonly']) !!}
                <span class="input-group-btn">
                    <button class="btn default" type="button">
                        <i class="fa fa-calendar"></i>
                    </button>
                </span>
            </div>
            {!! $errors->first('tanggal_lahir', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('nama_ortu') ? 'has-error' : '' }}">
        {!! Form::label('nama_ortu','Nama Orang Tua',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-6">
            {!! Form::text('nama_ortu', null, ['class'=>'form-control']) !!}
            {!! $errors->first('nama_ortu', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('hp_ortu') ? 'has-error' : '' }}">
        {!! Form::label('hp_ortu','No Telp Orang Tua',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-4">
            {!! Form::text('hp_ortu', null, ['class'=>'form-control']) !!}
            {!! $errors->first('hp_ortu', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('kelas_id') ? 'has-error' : '' }}"">
        {!! Form::label('kelas_id','Jenis Kelamin',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-4">
            {!! Form::select('kelas_id', [''=>''] + App\Models\Kelas::pluck('deskripsi','id')->toArray(), null, ['class'=>'form-control select2me']) !!}
            {!! $errors->first('kelas_id', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>
<div class="form-actions">
    <div class="row">
        <div class="col-md-offset-3 col-md-9">
            <button type="submit" class="btn green">Submit</button>
            <a href="{{ URL::previous() }}" type="button" class="btn default">Cancel</a>
        </div>
    </div>
</div>  

resources/views/siswa/create.blade.php
@extends('layouts.app')

@section('content')
<div class="page-content">
    <div class="page-head">
        <div class="page-title">
            <h1>Data Siswa</h1>
        </div>
        <div class="page-toolbar">
            @yield('page-toolbar')
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Dashboard</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('siswa.index') }}">Data Siswa</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Tambah</span>
        </li>
    </ul>

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-fit portlet-form bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-users font-green"></i>
                        <span class="caption-subject bold uppercase">Tambah Siswa</span>
                    </div>
                    <div class="tools"> </div>
                </div>
                <div class="portlet-body">
                    {!! Form::open(['url'=>route('siswa.store'), 'method'=>'POST', 'class'=>'form-horizontal']) !!}
                        @include('siswa._form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/siswa/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="page-content">
    <div class="page-head">
        <div class="page-title">
            <h1>Data Siswa</h1>
        </div>
        <div class="page-toolbar">
            @yield('page-toolbar')
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Dashboard</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('siswa.index') }}">Data Siswa</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Edit</span>
        </li>
    </ul>

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-users font-green"></i>
                        <span class="caption-subject bold uppercase">Edit Siswa</span>
                    </div>
                    <div class="tools"> </div>
                </div>
                <div class="portlet-body">
                    {!! Form::model($siswa->toArray(), ['url'=>route('siswa.update', $siswa->id), 'method'=>'PUT', 'class'=>'form-horizontal']) !!}
                        @include('siswa._form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/siswa/index.blade.php
@extends('layouts.app')

@section('page-actions')
<div class="page-actions">
    <div class="btn-group">
        <button type="button" class="btn red-haze btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
            <span class="hidden-sm hidden-xs">Tambah&nbsp;</span>
            <i class="fa fa-angle-down"></i>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li>
                <a href="{{ route('siswa.create') }}">
                    <i class="icon-plus"></i> Tambah 
                </a>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="icon-cloud-upload"></i> Import 
                </a>
            </li>
        </ul>
    </div>
</div>
@endsection

@section('content')
<div class="page-content">
    <div class="page-head">
        <div class="page-title">
            <h1>Data Siswa</h1>
        </div>
        <div class="page-toolbar">
            @yield('page-toolbar')
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Dashboard</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Data Siswa</span>
        </li>
    </ul>

    @include('layouts._flash')

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-users font-green"></i>
                        <span class="caption-subject bold uppercase">Siswa</span>
                    </div>
                    <div class="tools"> </div>
                </div>
                <div class="portlet-body">
                    <div class="table-responsive">
                        {!! $html->table(['class'=>'table table-striped table-bordered table-hover dt-responsive','width'=>'100%']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
{!! $html->scripts() !!}
@endsection

resources/views/siswa/show.blade.php
@extends('layouts.app')

@section('content')
<div class="page-content">
    <div class="page-head">
        <div class="page-title">
            <h1>Data Siswa</h1>
        </div>
        <div class="page-toolbar">
            @yield('page-toolbar')
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Dashboard</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Data Siswa</span>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Detil</span>
        </li>
    </ul>

    @include('layouts._flash')

    <div class="row">
        <div class="col-md-12">
            <div class="profile-sidebar">
                <div class="portlet light profile-sidebar-portlet bordered">
                    <div class="profile-userpic">
                        <img src="http://lorempixel.com/200/200/?94419" class="img-responsive" alt=""> 
                    </div>
                    <div class="profile-usertitle">
                        <div class="profile-usertitle-name"> {{ $siswa->nama }} </div>
                        <div class="profile-usertitle-job">{{ $siswa->kelas->deskripsi }} </div>
                    </div>
                    <div class="profile-userbuttons">
                        <a href="{{ route('siswa.edit', $siswa) }}" type="button" class="btn btn-circle green btn-sm"><i class="fa fa-pencil"></i> Edit</a>
                    </div>
                    <div class="profile-usermenu">

                    </div>
                </div>
                <div class="portlet light bordered">
                    <div class="row list-separated">
                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <div class="uppercase profile-stat-title"> {{ $siswa->presensi()->where('status','H')->count() }} </div>
                            <div class="uppercase profile-stat-text"> Hadir </div>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <div class="uppercase profile-stat-title"> {{ $siswa->presensi()->where('status','I')->count() }} </div>
                            <div class="uppercase profile-stat-text"> Izin </div>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <div class="uppercase profile-stat-title"> {{ $siswa->presensi()->where('status','A')->count() }} </div>
                            <div class="uppercase profile-stat-text"> Alpha </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END BEGIN PROFILE SIDEBAR -->
            <!-- BEGIN PROFILE CONTENT -->
            <div class="profile-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light bordered">
                            <div class="portlet-title tabbable-line">
                                <div class="caption caption-md">
                                    <i class="icon-globe theme-font hide"></i>
                                    <span class="caption-subject font-blue-madison bold uppercase">Detil Siswa</span>
                                </div>
                                <ul class="nav nav-tabs">
                                    <li class="active">
                                        <a href="#tab_1_1" data-toggle="tab">Data Diri</a>
                                    </li>
                                    <li>
                                        <a href="#tab_1_2" data-toggle="tab">QRCode</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="portlet-body">
                                <div class="tab-content">
                                    <!-- PERSONAL INFO TAB -->
                                    <div class="tab-pane active" id="tab_1_1">
                                        <table class="table table-light table-hover">
                                            <tr>
                                                <td><strong>No Induk</strong></td>
                                                <td>{{ $siswa->nis }}</td>
                                            </tr>
                                            <tr>
                                                <td><strong>Nama Siswa</strong></td>
                                                <td>{{ $siswa->nama }}</td>
                                            </tr>
                                            <tr>
                                                <td><strong>Alamat</strong></td>
                                                <td>{{ $siswa->alamat }}</td>
                                            </tr>
                                            <tr>
                                                <td><strong>Jenis Kelamin</strong></td>
                                                <td>{{ $siswa->jenis_kelamin == 'L' ? 'Laki-Laki' : 'Perempuan' }}</td>
                                            </tr>
                                            <tr>
                                                <td><strong>Tempat Lahir</strong></td>
                                                <td>{{ $siswa->tempat_lahir }}</td>
                                            </tr>
                                            <tr>
                                                <td><strong>Tanggal Lahir</strong></td>
                                                <td>{{ $siswa->tempat_lahir }}</td>
                                            </tr>
                                            <tr>
                                                <td><strong>Nama Orang Tua</strong></td>
                                                <td>{{ $siswa->nama_ortu }}</td>
                                            </tr>
                                            <tr>
                                                <td><strong>HP Orang Tua</strong></td>
                                                <td>{{ $siswa->hp_ortu }}</td>
                                            </tr>
                                            <tr>
                                                <td><strong>Kelas</strong></td>
                                                <td>{{ $siswa->kelas->deskripsi }}</td>
                                            </tr>
                                        </table>
                                    </div>
                                    <div class="tab-pane" id="tab_1_2">
                                        <div class="center-block">
                                            <img class="img-responsive center-block" src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->size(300)->generate($siswa->kode_qr)) !!} ">
                                            <p class="text-center">
                                                <a href="data:image/png;base64, {!! base64_encode(QrCode::format('png')->size(300)->generate($siswa->kode_qr)) !!} " download="qrcode.png" class="btn btn-primary text-center"><i class="fa fa-download"></i> Download</a>

                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END PROFILE CONTENT -->
        </div>
    </div>
</div>
@endsection