routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout');

Route::group(['middleware'=>'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('siswa', 'SiswaController');
    Route::get('download-qrcode/{id}', 'SiswaController@downloadQrcode')->name('downloadqrcode.siswa');
    Route::resource('kelas', 'KelasController');
    Route::resource('presensi', 'PresensiController', ['only' => ['index', 'create', 'store','update']]);
    Route::resource('mutasi', 'MutasiController');
    Route::resource('akademik', 'AkademikController');
    Route::get('/pengaturan', 'PengaturanController@index')->name('pengaturan.index');
    Route::post('/pengaturan', 'PengaturanController@update')->name('pengaturan.update');

    Route::get('laporan', 'PresensiController@laporan')->name('laporan.presensi');
    Route::any('scan-qrcode', 'PresensiController@scanQrcode')->name('scanqrcode.presensi');
});

app/Models/Kelas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    protected $table = 'kelas';
    protected $fillable = ['deskripsi'];

    public function siswa()
    {
        return $this->hasMany('App\Models\Siswa');
    }

    public function presensi()
    {
        return $this->hasMany('App\Models\Presensi');
    }
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kelas;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class KelasController extends Controller
{

    public function index(Request $request, Builder $htmlBuilder)
    {
        if ($request->ajax()) {
            return Datatables::of(Kelas::all())
                ->addColumn('action', function($kelas) {
                    return view('vendor.datatables._action_edit_delete', [
                        'edit_url' => route('kelas.edit', $kelas->id),
                        'model' => $kelas,
                        'form_url' => route('kelas.destroy', $kelas->id),
                        'confirm_message' => 'Anda yakin ingin menghapus '.$kelas->deskripsi.'?'
                    ]);
                })->make(true);
        }

        $html = $htmlBuilder
            ->addColumn(['data'=>'id','name'=>'id','title'=>'ID','class'=>'all'])
            ->addColumn(['data'=>'deskripsi','name'=>'deskripsi','title'=>'Deskripsi','class'=>'all'])
            ->addColumn(['data'=>'action','name'=>'action','title'=>'Action']);

        return view('kelas.index')->with(compact('html'));
    }

    public function create()
    {
        return view('kelas.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'deskripsi' => 'required|unique:kelas,deskripsi',
        ], [
            'deskripsi.required' => 'Kelas harus diisi'
        ]);

        $kelas = Kelas::create($request->all());

        $request->session()->flash('flash_notification', [
            'level' => 'success',
            'message' => 'Berhasil menyimpan '. $kelas->deskripsi
        ]);

        return redirect()->route('kelas.index');
    }

    public function edit($id)
    {
        $kelas = Kelas::findOrFail($id);
        return view('kelas.edit')->with(compact('kelas'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'deskripsi' => 'required|unique:kelas,deskripsi,'.$id,
        ], [
            'deskripsi.required' => 'Kelas harus diisi'
        ]);

        $kelas = Kelas::findOrFail($id);
        $kelas->update($request->all());

        $request->session()->flash('flash_notification', [
            'level' => 'success',
            'message' => 'Berhasil menyimpan '. $kelas->deskripsi
        ]);

        return redirect()->route('kelas.index');
    }

    public function destroy(Request $request, $id)
    {
        Kelas::destroy($id);

        $request->session()->flash('flash_notification', [
            'level' => 'success',
            'message' => 'Data kelas berhasil dihapus'
        ]);

        return redirect()->route('kelas.index');
    }
}

resources/views/kelas/_form.blade.php
<div class="form-body">
    @include('layouts._flash')

    <div class="form-group {{ $errors->has('deskripsi') ? 'has-error' : '' }}">
        {!! Form::label('deskripsi','Kelas',['class'=>'control-label col-md-3']) !!}
        <div class="col-md-4">
            {!! Form::text('deskripsi', null, ['class'=>'form-control']) !!}
            {!! $errors->first('deskripsi', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    
</div>
<div class="form-actions">
    <div class="row">
        <div class="col-md-offset-3 col-md-9">
            <button type="submit" class="btn green">Submit</button>
            <a href="{{ URL::previous() }}" type="button" class="btn default">Cancel</a>
        </div>
    </div>
</div>  

resources/views/kelas/create.blade.php
@extends('layouts.app')

@section('content')
<div class="page-content">
    <div class="page-head">
        <div class="page-title">
            <h1>Data Kelas</h1>
        </div>
        <div class="page-toolbar">
            @yield('page-toolbar')
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Dashboard</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('kelas.index') }}">Data Kelas</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Tambah</span>
        </li>
    </ul>

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-fit portlet-form bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-users font-green"></i>
                        <span class="caption-subject bold uppercase">Tambah Kelas</span>
                    </div>
                    <div class="tools"> </div>
                </div>
                <div class="portlet-body">
                    {!! Form::open(['url'=>route('kelas.store'), 'method'=>'POST', 'class'=>'form-horizontal']) !!}
                        @include('kelas._form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kelas/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="page-content">
    <div class="page-head">
        <div class="page-title">
            <h1>Data Kelas</h1>
        </div>
        <div class="page-toolbar">
            @yield('page-toolbar')
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Dashboard</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('kelas.index') }}">Data Kelas</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Edit</span>
        </li>
    </ul>

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-users font-green"></i>
                        <span class="caption-subject bold uppercase">Edit Kelas</span>
                    </div>
                    <div class="tools"> </div>
                </div>
                <div class="portlet-body">
                    {!! Form::model($kelas->toArray(), ['url'=>route('kelas.update', $kelas->id), 'method'=>'PUT', 'class'=>'form-horizontal']) !!}
                        @include('kelas._form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kelas/index.blade.php
@extends('layouts.app')

@section('page-actions')
<div class="page-actions">
    <div class="btn-group">
        <button type="button" class="btn red-haze btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
            <span class="hidden-sm hidden-xs">Tambah&nbsp;</span>
            <i class="fa fa-angle-down"></i>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li>
                <a href="{{ route('kelas.create') }}">
                    <i class="icon-plus"></i> Tambah 
                </a>
            </li>
        </ul>
    </div>
</div>
@endsection

@section('content')
<!-- BEGIN CONTENT BODY -->
<div class="page-content">
    <!-- BEGIN PAGE HEAD-->
    <div class="page-head">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1>Data Kelas</h1>
        </div>
        <!-- END PAGE TITLE -->
        <!-- BEGIN PAGE TOOLBAR -->
        <div class="page-toolbar">
            @yield('page-toolbar')
        </div>
        <!-- END PAGE TOOLBAR -->
    </div>
    <!-- END PAGE HEAD-->
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Dashboard</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Data Kelas</span>
        </li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
    @include('layouts._flash')
    <!-- BEGIN PAGE BASE CONTENT -->

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-settings font-green"></i>
                        <span class="caption-subject bold uppercase">Kelas</span>
                    </div>
                    <div class="tools"> </div>
                </div>
                <div class="portlet-body">
                    <div class="table-responsive">
                        {!! $html->table(['class'=>'table table-striped table-bordered table-hover dt-responsive','width'=>'100%']) !!}
                    </div>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    <!-- END PAGE BASE CONTENT -->
</div>
<!-- END CONTENT BODY -->
@endsection

@section('scripts')
{!! $html->scripts() !!}
@endsection