routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout');

Route::group(['middleware'=>'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('siswa', 'SiswaController');
    Route::get('download-qrcode/{id}', 'SiswaController@downloadQrcode')->name('downloadqrcode.siswa');
    Route::resource('kelas', 'KelasController');
    Route::resource('presensi', 'PresensiController', ['only' => ['index', 'create', 'store','update']]);
    Route::resource('mutasi', 'MutasiController');
    Route::resource('akademik', 'AkademikController');
    Route::get('/pengaturan', 'PengaturanController@index')->name('pengaturan.index');
    Route::post('/pengaturan', 'PengaturanController@update')->name('pengaturan.update');

    Route::get('laporan', 'PresensiController@laporan')->name('laporan.presensi');
    Route::any('scan-qrcode', 'PresensiController@scanQrcode')->name('scanqrcode.presensi');
});

resources/views/layouts/_flash.blade.php
@if (session()->has('flash_notification.message'))
<div class="alert alert-{{ session()->get('flash_notification.level') }} alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    {!! session()->get('flash_notification.message') !!}
</div>
@endif

resources/views/layouts/_footer.blade.php
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner"> {{ date('Y') }} &copy; gAbsensi.
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- END FOOTER -->

resources/views/layouts/_header.blade.php
<div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner ">
        <div class="page-logo">
            <a href="{{ url('/') }}" class="logo-default">
                {{ Helper::pengaturan()->nama_aplikasi }}
            </a>
            <div class="menu-toggler sidebar-toggler">
            </div>
        </div>
        
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
        
        @yield('page-actions')
        
        <div class="page-top">
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    <li class="separator hide"> </li>
                    @if(Auth::user())
                        <li class="dropdown dropdown-user dropdown-extended">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <span class="username username-hide-on-mobile"> Hi,  {{ Auth::user()->name }} </span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                <li>
                                    <a href="{{ route('pengaturan.index') }}"><i class="icon-user"></i> Pengaturan </a>
                                </li>
                                <li>
                                    <a href="{{ url('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit()"><i class="icon-key"></i> Keluar </a>
                                    <form action="{{ url('/logout') }}" id="logout-form" method="POST" style="display:none">{{ csrf_field() }}</form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"> </div>

resources/views/layouts/_sidebar.blade.php
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <ul class="page-sidebar-menu   " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            <li class="nav-item {{ Route::is('dashboard') ? 'active' : '' }}">
                <a href="{{ url('/') }}" class="nav-link">
                    <i class="icon-home"></i>
                    <span class="title">Dashboard</span>
                </a>
            </li>
            <li class="heading">
                <h3 class="uppercase">Presensi</h3>
            </li>
            <li class="nav-item {{ Route::is('scanqrcode.presensi') ? 'active' : '' }}">
                <a href="{{ route('scanqrcode.presensi') }}" class="nav-link " target="_blank">
                    <i class="icon-camera"></i>
                    <span class="title">Scan QRCode</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('presensi.*') ? 'active' : '' }}">
                <a href="{{ route('presensi.index') }}" class="nav-link ">
                    <i class="icon-list"></i>
                    <span class="title">Daftar Presensi</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('laporan.presensi') ? 'active' : '' }}">
                <a href="{{ route('laporan.presensi') }}" class="nav-link">
                    <i class="icon-doc"></i>
                    <span class="title">Laporan</span>
                </a>
            </li>
            <li class="heading">
                <h3 class="uppercase">Master</h3>
            </li>
            <li class="nav-item {{ Route::is('siswa.*') ? 'active' : '' }}">
                <a href="{{ route('siswa.index') }}" class="nav-link">
                    <i class="icon-users"></i>
                    <span class="title">Data Siswa</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('kelas.*') ? 'active' : '' }}">
                <a href="{{ route('kelas.index') }}" class="nav-link">
                    <i class="icon-graduation"></i>
                    <span class="title">Data Kelas</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('mutasi.*') ? 'active' : '' }}">
                <a href="{{ route('mutasi.index') }}" class="nav-link">
                    <i class="icon-directions"></i>
                    <span class="title">Mutasi Siswa</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('akademik.*') ? 'active' : '' }}">
                <a href="{{ route('akademik.index') }}" class="nav-link">
                    <i class="icon-paper-clip"></i>
                    <span class="title">Tahun Ajaran</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('pengaturan.*') ? 'active' : '' }}">
                <a href="{{ route('pengaturan.index') }}" class="nav-link">
                    <i class="icon-settings"></i>
                    <span class="title">Pengaturan</span>
                </a>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>
<!-- END SIDEBAR -->

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>{{ Helper::pengaturan()->nama_aplikasi }}</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'gAbsensi') }}</title>
    
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="{{ elixir('css/all.css') }}">
        <script>
            window.gAbsensi = <?php echo json_encode([
                'csrfToken' => csrf_token(),
            ]); ?>
        </script>
        
        <link rel="shortcut icon" href="/favicon.ico" /> 
    </head>

    <body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
        @include('layouts._header')

        <div class="page-container">
            <div class="page-sidebar-wrapper">
                @include('layouts._sidebar')
            </div>
            <div class="page-content-wrapper">
                @yield('content')
            </div>
        </div>

        @include('layouts._footer')
        
        <script src="{{ elixir('js/all.js') }}"></script>

        @yield('scripts')
    </body>
</html>

resources/views/layouts/login.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <title>{{ config('app.name', 'gAbsensi')}} :: Login</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <link rel="stylesheet" href="{{ elixir('css/login.css') }}">
        <link rel="shortcut icon" href="/favicon.ico" /> </head>

    <body class=" login">
        <div class="user-login-5">
            <div class="row bs-reset">
                <div class="col-md-6 login-container bs-reset">
                    <a class="login-logo login-6" >{{ config('app.name', 'gAbsensi')}}</a>
                    <div class="login-content">
                        @yield('content')
                    </div>
                    <div class="login-footer">
                        <div class="row bs-reset">
                            <div class="col-xs-5 bs-reset">
                            </div>
                            <div class="col-xs-7 bs-reset">
                                <div class="login-copyright text-right">
                                    <p>Copyright &copy; gAbsensi {{ date('Y') }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 bs-reset">
                    <div class="login-bg"> </div>
                </div>
            </div>
        </div>
        <script src="{{ elixir('js/login.js') }}"></script>
    </body>

</html>

resources/views/layouts/presensi.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>{{ config('app.name', 'gAbsensi')}} :: Presensi</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'gAbsensi') }}</title>
    
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="{{ elixir('css/all.css') }}">
        <script>
            window.gAbsensi = <?php echo json_encode([
                'csrfToken' => csrf_token(),
            ]); ?>
        </script>
        
        <link rel="shortcut icon" href="/favicon.ico" /> 
    </head>

    <body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
        @include('layouts._header')

        <div class="page-container">
            <div class="page-content-wrapper">
                @yield('content')
            </div>
        </div>

        @include('layouts._footer')
        
        <script src="{{ elixir('js/all.js') }}"></script>

        @yield('scripts')
    </body>
</html>